### ISSUE TITLE
instance_id is not getting updated in the state table. so the instance is neither getting stopped nor started, with the scheduler version 1.3.2

### ISSUE THREAD

**Issue by JagadeswarYaramala-moodys** [aws-solutions/aws-instance-scheduler#236]

**Comment by JagadeswarYaramala-moodys** [comment]
Hi Team,

we are using old scheduler and now have decided to use the latest scheduler and deployed the version 1.3.2 in which we have copied all our old schedule rules and state table also and now to test the latest scheduler before deleting the old scheduler we have disabled the old scheduler event rule and launched a new instance and tagged it with stopped but it didn't stop the instance. then again we enabled the previous version of scheduler it picked that and stopped the instance. can we know what may be the issue.

the previous version that we are using is:   version v1.2.0

**Comment by praveenis** [comment]
Hi @JagadeswarYaramala-moodys 

You don't have to delete the old scheduler version, You can directly Update the existing stack by Replacing current stack with newer version of the solution 1.3.3. 

Newer version will use the existing schedules. Since your version is too old, It's safer to backup the schedules form config table before upgrading.

Please let us know incase of any issues with the upgrade.

Thanks,
Praveen
