### ISSUE TITLE
Fails to operate on a set of instances when one instance is unstartable

### ISSUE THREAD

**Issue by schasan** [aws-solutions/aws-instance-scheduler#266]
DEBUG   : Listing instance EC2:i-0c2d3cf2131aff2e4 (eclaws014) in region eu-central-1 with instance type t3a.xlarge to be started by scheduler
INFO    : Starting instances EC2:i-07d0d2f75d3eb5efe (C7-DevEnv-211), EC2:i-052b2aec62fa2ffe9 (lp279_settleDev_2), EC2:i-078e8ecc539aa56ee (ADCashICSD_fh231_DDR_DB (james)), EC2:i-06daa648609dcabbd (C7-DevEnv-212), EC2:i-0a1329130d6073ae2 (ec2devdbacont0732), EC2:i-0b3e12e4ad4b2e51e, EC2:i-051a9a0f78d2b975a (kafka-RegHub-d2-3), EC2:i-0365e234f56dd38b7 (eclaws009), EC2:i-0c2d3cf2131aff2e4 (eclaws014), EC2:i-0d8ce2c833342f06e (eclaws012), EC2:i-02343de11fb9f875a (eclaws011), EC2:i-09bf3b7520e177a45 (eclaws008), EC2:i-09fdede4ca94ed65e (eclaws013), EC2:i-09677807a0f62659d (eclaws007), EC2:i-02ae0858e884d109b (eclaws010) in region eu-central-1
ERROR   : Error starting instances i-0b3e12e4ad4b2e51e,i-051a9a0f78d2b975a,i-0365e234f56dd38b7,i-0c2d3cf2131aff2e4,i-0d8ce2c833342f06e, (An error occurred (InvalidParameterValue) when calling the StartInstances operation: Invalid value 'i-0b3e12e4ad4b2e51e' for instanceId. Instance does not have a volume attached at root (/dev/sda1))

**Comment by gockle** [comment]
@schasan the solution starts/stops the ec2 instances in batches, if any one EC2 instance in the batch is having issues like missing EBS volume the scheduling is skipped for the entire group/batch of ec2 instances. The batch size can be modified to a lower value from the default value of 5 by modifying the Lambda environment variable START_EC2_BATCH_SIZE.

**Comment by schasan** [comment]
The stuff should be failsafe, Users complained about their 3 instances not started.
It should be easy to fall back from batch to single processing if the boto3 fails.
Two additional lines of code. Shall I try a PR? Is it maintained here?

**Comment by gockle** [comment]
@schasan The current implementation limits the number of API calls made to the EC2 service, this decision was taken to address throttling issues being generated, if the solution switches to make single instance API calls, scaling will be a problem, the compromise is submit API requests in batches, there are other options being explored for the solution for a redesign, if the recommendation above has resolved the issue, I would let it be at that, at this point we don't have plans to incorporate any new PR's into the current version of the code base, but this issue is being tracked by the team, so there will be a solution for the design limitation.
