### ISSUE TITLE
ssm automation steps remain pending

### ISSUE THREAD

**Issue by ashraf133** [aws-solutions/aws-instance-scheduler#288]
**Describe the bug**
ssm automation status is success but its are steps pending ( there is not resources to stop or start )
This should cost money until it is manually cancelled

**To Reproduce**
Install aws scheduler and register accounts, the ssm execution will try for exemple to stop rds ( which doesnt exist )
**Expected behavior**
automation in success or aborted and its steps also

**Comment by gockle** [comment]
Hi @ashraf133 The pending state of steps within the main automation step does not count towards the overall Automation limit, if you check the steps don't have a start and stop times, they are kept in that state by design by the Automation service to indicate that no need to run them. If there are no tagged instances available in that account/region the automation ends and account will not be billed additionally, if you observe any different reach out to the AWS Support > Automation team for further information and clarification.

**Comment by ashraf133** [comment]
Thank you for the answer :)
