### ISSUE TITLE
EC2 not stopped when using 2 periods for a given schedule

### ISSUE THREAD

**Issue by ajean-cloud** [aws-solutions/aws-instance-scheduler#293]
Hello,

Currently facing an issue (misconfiguration?) with the Instance scheduler solution. I've got 1 schedule:
`{
  "type": {
    "S": "schedule"
  },
  "name": {
    "S": "fr-start-stop"
  },
  "timezone": {
    "S": "Europe/Paris"
  },
  "description": {
    "S": "start_stop_weekdays"
  },
  "periods": {
    "SS": [
      "start-stop",
      "stop-8pm"
    ]
  }
}`

with 2 distincts periods: 
- A first one which starts the EC2 at 11:15AM and stops it at 1PM
`{
  "type": {
    "S": "period"
  },
  "name": {
    "S": "start-stop"
  },
  "begintime": {
    "S": "11:15"
  },
  "endtime": {
    "S": "13:00"
  },
  "description": {
    "S": "11:15AM-1PM_weekdays"
  },
  "weekdays": {
    "SS": [
      "mon-fri"
    ]
  }
}`

- Another one which stops the EC2 at 8PM if the machine has been booted manually between 1PM and 8PM
`{
    "type": {
      "S": "period"
    },
    "name": {
      "S": "stop-8pm"
    },
    "description": {
      "S": "stop the instance at 8pm"
    },
    "endtime": {
      "S": "20:00"
    }
  }
  `
  
**But the EC2 machine is not stopped at 1PM as defined in the 1st period declared in my schedule.** It seems the Lambda function is not able to stops the machine if there is no start time for the next period of a schedule. Is that normal?
FYI: in the Cloudtrail events I can see that the EC2 is well stopped at 8PM, restarted at 11:15AM but not stopped at 1PM as expected.

Thank you very much in advance for your support!

**Comment by aaajean** [comment]
Not sure if it can help but it is mentioned in the AWS documentation: 

Each schedule must contain at least one period that defines the time(s) the instance should run. A
schedule can contain more than one period. When more than one period is used in a schedule, the
Instance Scheduler will apply the appropriate start action when at least one of the period rules is true.
For more information, refer to Period Rules (p. 8)

**Comment by gockle** [comment]
Hi @aaajean 

Each period is meant to provide the duration for which instance is meant to be in `running` state. So as per the configuration provided

* period: start-stop, begintime 11:15 and endtime: 13:00
* period: stop-8pm, begintime N/A and endtime: 20:00

The duration for the schedule defined with the periods for which the instance should be available is 11:15 to 20:00.

Reference to the documentation:

___If your schedule contains multiple periods, we recommend that you specify both a begintime and endtime in your period. If no time is specified, this solution will use the time specified in the other periods to determine when to start and stop your instances. For example, if in one period you specify a begintime of 9 am with no endtime because you want the instance to run until you manually stop it, AWS Instance Scheduler will stop the instance at 00:00 am the following day. AWS Instance Scheduler will evaluate whether to keep the instance started or stopped until it finds another period for that specific day.___

Review the section `Start and stop times` in the documenatation [here](https://docs.aws.amazon.com/solutions/latest/instance-scheduler/components.html)
