### ISSUE TITLE
different region support for different account

### ISSUE THREAD

**Issue by luteamol** [aws-solutions/aws-instance-scheduler#296]
Hi Team,
I am using 1 instance scheduler to support multiple accounts.
Is it possible to enable different set of region for different account ?
for example: I want to enable instance scheduler for Frankfurt, Ireland region for account A and Ireland, Paris region for account B.
Current config entry in dynamoDB will enable the mentioned regions for all the accounts. There is no option to specify regions specific to a particular account.

Thanks,
Amol

**Comment by gockle** [comment]
Hi @luteamol You can deploy multiple stacks of instance scheduler and manage the accounts/regions in different combinations?

**Comment by luteamol** [comment]
Thanks @gockle !
Managing multiple instances of instance scheduler would make it very complicated.
I would request to take this as a feature request.  A new config entry in Instance-Scheduler-ConfigTable should be able to identify regions for any account.
For example, entry-1 would define certain regions and related account list, while entry-2 will define another set of regions and its account list.

Thanks,
Amol

**Comment by gockle** [comment]
Hi @luteamol At this point there are no planned releases for this solution, the requirement mentioned above poses some unique changes,
* The solution currently loads all the configs and starts multiple lambda executions for each service based on the account-region combinations in the file `cloudwatch_event_handler.py` the method `handle_request` and `_run_schedulers_as_lambda`. 
* If the solution has to implement a requirement where each account has different combinations of regions, the solution has to be modified extensively in the UI (CloudFormation template) and the config (DynamoDB table) where the data is stored along with modifications for the python file.

This would entail making changes which will create issues for all scenario where the stacks have to be updated to the latest version from 1.4.0. Hence it's unlikely this feature can be implemented due to both the effort and the unlikely situation that the back compatibility is broken due to incompatible update options. 

Recommendations:
* Run multiple stacks each stack will have unique combinations of regions and accounts
* Modify the `cloudwatch_event_handler.py` file in your stack both the `handle_request` and `_run_schedulers_as_lambda` should be modified.

**Comment by luteamol** [comment]
Thanks @gockle for detailed explanation !
I am closing this issue.
